### ISSUE TITLE
Incompatible with MoreCulling mod

### ISSUE THREAD

**Issue by NaiNonTH** [isXander/CullLessLeaves#14]
As the title said, the CullLessLeaves mod cannot be installed with the MoreCulling mod, as it results in the game crashing unexpectedly.

Ref.
https://github.com/fxmorin/MoreCulling/issues/6#issuecomment-1146642291

**Comment by FxMorin** [comment]
Please provide a crash log

**Comment by NaiNonTH** [comment]
Trying recreating an error. One moment.

**Comment by NaiNonTH** [comment]
<details>
<summary>latest.log</summary>
```
[23:26:34] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.6
[23:26:34] [main/WARN]: Warnings were found!
 - Mod 'Debugify' (debugify) 1.11.0 conflicts with any version of mod 'Title Fix' (title-fix), which is present with the following versions: 1.0.1+MC1.17.1!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Debugify' (debugify) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
[23:26:34] [main/INFO]: Loading 162 mods:
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- ambientsounds 2.5.0
	- antighost 1.18.2-fabric0.47.10-1.1.4
	- beautifiedchatclient-fabric 1.0
	- betterbiomeblend 1.18.2-1.3.5-fabric
	- betterblockoutline 1.4.2-1.18.1
	- betterf3 1.2.5
	- betterfpsdist 1.18-1.8
	- betterpingdisplay 1.1.1
	- bettertaskbar 1.3
	- blanket-client-tweaks 1.0.3
	- blockify 1.2.1
	- c2me 0.2.0+alpha.7.0
	- caffeineconfig 1.1.0 via sodium-extra
	- capetweaks 1.0.0
	- chatsounds 1.1.3
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- collective-fabric 4.20
	- com_github_llamalad7_mixinextras 0.0.10 via debugify
	- com_github_meteordevelopment_starscript 0.1.9 via respackopts
	- com_ishland_c2me_libs_ 0.2.0+alpha.7.0 via c2me
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_typesafe_config 1.4.2 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- compactchat 1.1.1
	- confabricate 3.0.0-SNAPSHOT+4.1.2 via purpurclient
	- continuity 1.1.0+1.18.2
	- creativecore 2.6.10
	- crowdin-translate 1.4+1.18.2 via antighost
	- cull-less-leaves 1.0.1
	- debugify 1.11.0
	- draggable-resource-packs 2.0.0
	- dyed 1.0.2
	- dynamicfps 2.1.0
	- eatinganimationid 1.8
	- effective 1.2.1
	- enhanced-searchability 2.0.3
	- enhancedblockentities 0.6+1.18.2
	- entity_texture_features 3.0.3
	- entitycollisionfpsfix 1.0.0
	- entityculling 1.5.1
	- extendedclouds 1.1.1
	- fabric 0.54.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.1+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.6+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-dimensions-v1 2.1.19+ffb2c71e60 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.16+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.0+85719ab760 via fabric
	- fabric-item-groups-v0 0.3.13+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.4+d8d7804a60 via fabric
	- fabric-loot-api-v2 1.0.0+e747827960 via fabric
	- fabric-loot-tables-v1 1.1.0+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.2+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.2+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.1+e747827960 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.2+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.6
	- fabricskyboxes 0.5.5
	- fallingleaves 1.11.1+1.18.2
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- firstperson 2.1.0
	- fullbrightnesstoggle-fabric 1.3
	- illuminations 1.10.4
	- impactfulweather 2.4.7
	- inan 1.0.0+77bd8c6
	- indium 1.0.3+mc1.18.2
	- io_leangen_geantyref_geantyref 1.3.13 via confabricate
	- iris 1.2.5-beta.4
	- itemmodelfix 1.0.3+1.18
	- java 17
	- kirin 1.10.0 via presencefootsteps
	- kommandlib 0.1.0-1.18.1 via betterblockoutline
	- krypton 0.1.9
	- languagereload 1.2.1
	- lazydfu 0.1.2
	- libjf-base 2.8.1 via respackopts
	- libjf-data-manipulation-v0 2.8.1 via respackopts
	- libjf-unsafe-v0 2.8.1 via respackopts
	- lithium 0.7.10
	- loadingscreentips 1.0.1
	- make_bubbles_pop 0.0.1-1.18.2
	- malilib 0.12.1
	- memoryleakfix 1.18.2-0.3.5
	- midnightlib 0.4.0 via blockify
	- minecraft 1.18.2
	- modmanager 1.2.3+1.18
	- modmenu 3.2.2
	- moreculling 1.18.2-0.1.2
	- no-autojump 1.0
	- no-resource-pack-warnings 1.0.0
	- notenoughanimations 1.6.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_spongepowered_configurate-core 4.1.2 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.2 via confabricate
	- org_spongepowered_configurate-gson 4.1.2 via confabricate
	- org_spongepowered_configurate-hocon 4.1.2 via confabricate
	- oscimate_soulflame 1.0.0
	- physicsmod 2.7.5
	- presencefootsteps 1.5.0
	- purpurclient 1.18.2-3
	- raised 1.1.1
	- reeses-sodium-options 1.4.2
	- resounding 1.0.0-bc.9
	- respackopts 2.10.2
	- shaderreload 1.7
	- skinlayers 1.4.6-mc1.18.2
	- smoothchunk 1.18.2-1.9
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.4+mc1.18.2-build.39
	- spruceui 3.3.3+1.18 via compactchat
	- sspb 2.0.0
	- starlight 1.0.2+fabric.89b8d9f
	- thorium 1.2.1
	- tiefix 1.10.0
	- title-fix 1.0.1+MC1.17.1
	- uiinputundo 1.2.0
	- visualoverhaul 4.1.0
	- vmp 0.2.0+beta.3.17
	- waveycapes 1.2.0
[23:26:35] [main/INFO]: LibJF unsafe init completed
[23:26:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/NoncanbeZaza/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[23:26:35] [main/INFO]: Compatibility level set to JAVA_17
[23:26:35] [main/INFO]: Configuration loaded successfully after 231.6663ms
[23:26:35] [main/INFO]: Successfully loaded configuration for C2ME
[23:26:35] [main/INFO]: Initializing C2ME Compatibility Module
[23:26:35] [main/WARN]: Reference map 'confabricate-accessor-refmap.json' for confabricate.accessor.mixins.json could not be read. If this is a development environment you can ignore this message
[23:26:36] [main/INFO]: Preloading Debugify
[23:26:36] [main/INFO]: Done.
[23:26:36] [main/INFO]: Discovered LibJF asm plugin in libjf-data-manipulation-v0
[23:26:36] [main/WARN]: Reference map 'libjf-unsafe-v0-refmap.json' for libjf-unsafe-v0.mixins.json could not be read. If this is a development environment you can ignore this message
[23:26:36] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 2 override(s) found
[23:26:36] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[23:26:36] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[23:26:37] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[23:26:37] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton, vmp]) disables it and children
[23:26:37] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[23:26:37] [main/WARN]: [SSPB] Reese's Sodium Options >= 1.4.2 detected. Mixin 'rynnavinx.sspb.mixin.reeses_sodium_options.MixinSodiumVideoOptionsScreen' will not be enabled
[23:26:37] [main/WARN]: Error loading class: carpet/patches/EntityPlayerMPFake (java.lang.ClassNotFoundException: carpet/patches/EntityPlayerMPFake)
[23:26:37] [main/INFO]: Adding mixins: [None]
[23:26:37] [main/INFO]: I used the json to destroy the json
[23:26:39] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[23:26:39] [DefaultDispatcher-worker-1/INFO]: Checking for mod updates...
[23:26:39] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[23:26:40] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[23:26:40] [main/ERROR]: Mixin apply for mod cull-less-leaves failed cull-less-leaves.mixins.json:BlockMixin from mod cull-less-leaves -> net.minecraft.class_2248: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_2248::shouldCullLeafSide with priority 1000 cannot inject into net/minecraft/class_2248::method_9607(Lnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z merged by ca.fxco.moreculling.mixin.Block_drawSideMixin with priority 1000 [PREINJECT Applicator Phase -> cull-less-leaves.mixins.json:BlockMixin from mod cull-less-leaves -> Prepare Injections ->  -> modifyExpressionValue$zjf000$shouldCullLeafSide(ZLnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2248::shouldCullLeafSide with priority 1000 cannot inject into net/minecraft/class_2248::method_9607(Lnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z merged by ca.fxco.moreculling.mixin.Block_drawSideMixin with priority 1000 [PREINJECT Applicator Phase -> cull-less-leaves.mixins.json:BlockMixin from mod cull-less-leaves -> Prepare Injections ->  -> modifyExpressionValue$zjf000$shouldCullLeafSide(ZLnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) [libjf-unsafe-v0-2.8.1-a8308e643d9bb0de.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
[23:26:40] [DefaultDispatcher-worker-1/INFO]: No update for ambientsounds found!
[23:26:40] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.6-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.6-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.8.1-a8308e643d9bb0de.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.6-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [cull-less-leaves.mixins.json:BlockMixin from mod cull-less-leaves] from phase [DEFAULT] in config [cull-less-leaves.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.8.1-a8308e643d9bb0de.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.6-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2248::shouldCullLeafSide with priority 1000 cannot inject into net/minecraft/class_2248::method_9607(Lnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z merged by ca.fxco.moreculling.mixin.Block_drawSideMixin with priority 1000 [PREINJECT Applicator Phase -> cull-less-leaves.mixins.json:BlockMixin from mod cull-less-leaves -> Prepare Injections ->  -> modifyExpressionValue$zjf000$shouldCullLeafSide(ZLnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.8.1-a8308e643d9bb0de.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.6-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
```
</details>
No Crash Report

Edit: made collapsible by Xander
Edit 2: idfk how to make the codeblock work in summaries

**Comment by FxMorin** [comment]
I currently overwrite that method due to how fabric-api supports `shouldDrawSide()`
The way I currently do it would run the vanilla way so you could just skip this mixin if my mod is present

**Comment by FxMorin** [comment]
Actually moving that code into the leafBlocks `isSideInvisible()` would make more sense for you implementation

**Comment by isXander** [comment]
> Actually moving that code into the leafBlocks `isSideInvisible()` would make more sense for you implementation

This is how I was trying to do it but unfortunately not enough params are passed to that method. (I need BlockPos)

**Comment by FxMorin** [comment]
Oh I see, ya that's a bit of a problem

**Comment by isXander** [comment]
tracking issue here. fxmorin/MoreCulling#7 MoreCulling overwrites fully. So this is not the fault of this mod.
