### ISSUE TITLE
Incompatible Mod Set (YetAnotherConfigLib)

### ISSUE THREAD

**Issue by AquaLawng** [isXander/CullLessLeaves#52]
Launching Minecraft 1.19.4 with CullLessLeaves 1.2.0 and YetAnotherConfigLib 3.0.2 produces the following error log:

> [15:43:54] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.21
[15:43:54] [ForkJoinPool-1-worker-5/WARN]: Mod lod uses the version 1.6.11a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '11a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:43:55] [main/WARN]: Mod resolution failed
[15:43:55] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE cull-less-leaves 1.2.0 {depends yet_another_config_lib_v3 @ [*]}, ROOT_FORCELOAD_SINGLE cull-less-leaves 1.2.0]
[15:43:55] [main/INFO]: Reason: [HARD_DEP cull-less-leaves 1.2.0 {depends yet_another_config_lib_v3 @ [*]}]
[15:43:55] [main/INFO]: Fix: add [add:yet_another_config_lib_v3 1 ([(-?,?)])], remove [], replace []
[15:43:55] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install yet_another_config_lib_v3, any version.
Unmet dependency listing:
	 - Mod 'Cull Less Leaves' (cull-less-leaves) 1.2.0 requires any version of yet_another_config_lib_v3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

**Comment by isXander** [comment]
Make sure you haven't got the forge version of YACL

**Comment by AquaLawng** [comment]
Ah, so I found the issue. It was the Fabric version of YACL, but it was somehow 3.0.2+1.20 rather than 3.0.2+1.19.4. Not sure how that happened as I created the modpack using CurseForge, but regardless, solved.

**Comment by AquaLawng** [comment]
Ah, so I found the issue. It was the Fabric version of YACL, but it was somehow 3.0.2+1.20 rather than 3.0.2+1.19.4. Not sure how that happened as I created the modpack using CurseForge, but regardless, solved.
