### ISSUE TITLE
crash with java 17

### ISSUE THREAD

**Issue by marlester-dev** [isXander/CullLessLeaves#67]
[modlist(1).md](https://github.com/user-attachments/files/17466197/modlist.1.md)
```java
[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_2248 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.7.jar:?]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_2248 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[fabric-loader-0.16.7-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	... 2 more
``` 
 fabric loader version 0.16.7
 mc 1.20.1
 no crash on 1.3.0
  possible reason: something was compiled with java 21

**Comment by JunnA420** [comment]
Yes, the mod was compiled with java 21, just figured out its this one

**Comment by memphismc** [comment]
getting this crash on fabric 1.20.1, loader 0.16.7, using cull less leaves 1.4.1+1.21 version
https://rlim.com/bfkJtQnSix

**Comment by ChickenDestroyer** [comment]
Same issue, looks to be a simple mistake by the creator/compiler.

**Comment by Fyoncle** [comment]
Same issue here.

**Comment by marlester-dev** [comment]
use 1.21-fabric 1.4.2+1.21-fabric

**Comment by Fyoncle** [comment]
> use 1.21-fabric 1.4.2+1.21-fabric

That happens IN 1.20.1 bro...

**Comment by ChickenDestroyer** [comment]
> use 1.21-fabric 1.4.2+1.21-fabric

Wrong version of Fabric Minecraft. The issue is with an update for 1.20.1 version of the mod, that you have compiled with a later version of Java, then what 1.20.1 can read. The fix is not to tell us to use a version of the mod that is for a DIFFERENT VERSION of Minecraft.
