### ISSUE TITLE
1.21.3 update?

### ISSUE THREAD

**Issue by puppie1997** [isXander/CullLessLeaves#71]
[16:39:54] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED cull-less-leaves 1.5.0 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE cull-less-leaves 1.5.0]
[16:39:54] [main/INFO]: Reason: [HARD_DEP cull-less-leaves 1.5.0 {depends minecraft @ [1.21]}]
[16:39:54] [main/INFO]: Fix: add [], remove [cull-less-leaves 1.5.0], replace []
[16:39:54] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Cull Less Leaves' (cull-less-leaves) 1.5.0 (C:\Users\jimmy\AppData\Roaming\ATLauncher\instances\QualityofLife\mods\CullLessLeaves-1.5.0.jar).
More details:
	 - Mod 'Cull Less Leaves' (cull-less-leaves) 1.5.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

I tried 1.4.2 as well

**Comment by SpiritOTHawk** [comment]
1.21.4 also
